// Currency and Country Constants

export interface Currency {
  code: string;
  name: string;
  symbol: string;
  country: string;
}

export const CURRENCIES: Currency[] = [
  { code: "USD", name: "US Dollar", symbol: "$", country: "United States" },
  { code: "EUR", name: "Euro", symbol: "€", country: "European Union" },
  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    country: "United Kingdom",
  },
  { code: "INR", name: "Indian Rupee", symbol: "₹", country: "India" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", country: "Japan" },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    country: "Australia",
  },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", country: "Canada" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", country: "Switzerland" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", country: "China" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", country: "Singapore" },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    country: "Hong Kong",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    country: "New Zealand",
  },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", country: "Sweden" },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    country: "South Korea",
  },
  { code: "MXN", name: "Mexican Peso", symbol: "$", country: "Mexico" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", country: "Brazil" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", country: "Russia" },
  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    country: "South Africa",
  },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", country: "Turkey" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", country: "Poland" },
  { code: "THB", name: "Thai Baht", symbol: "฿", country: "Thailand" },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    country: "Indonesia",
  },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", country: "Malaysia" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", country: "Philippines" },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    country: "Czech Republic",
  },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", country: "Israel" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", country: "Chile" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", country: "Pakistan" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", country: "Bangladesh" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", country: "Nepal" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", country: "Sri Lanka" },
  { code: "KES", name: "Kenyan Shilling", symbol: "Sh", country: "Kenya" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", country: "Nigeria" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", country: "Egypt" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", country: "Ukraine" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", country: "Vietnam" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", country: "Taiwan" },
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    country: "United Arab Emirates",
  },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", country: "Saudi Arabia" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", country: "Denmark" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", country: "Norway" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr", country: "Iceland" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", country: "Croatia" },
  { code: "RON", name: "Romanian Leu", symbol: "Lei", country: "Romania" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", country: "Bulgaria" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", country: "Hungary" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", country: "Belarus" },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    country: "Kazakhstan",
  },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", country: "Ukraine" },
  {
    code: "TMT",
    name: "Turkmenistan Manat",
    symbol: "m",
    country: "Turkmenistan",
  },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", country: "Qatar" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", country: "Kuwait" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", country: "Oman" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", country: "Jordan" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", country: "Lebanon" },
  { code: "CYP", name: "Cypriot Pound", symbol: "£", country: "Cyprus" },
  { code: "COP", name: "Colombian Peso", symbol: "$", country: "Colombia" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", country: "Peru" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", country: "Tunisia" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", country: "Algeria" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", country: "Morocco" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", country: "Afghanistan" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", country: "Iran" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", country: "Iraq" },
  { code: "SYP", name: "Syrian Pound", symbol: "£", country: "Syria" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", country: "Yemen" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", country: "Somalia" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س", country: "Sudan" },
  { code: "LYD", name: "Libyan Dinar", symbol: "د.ل", country: "Libya" },
  { code: "BYR", name: "Belarusian Ruble", symbol: "Br", country: "Belarus" },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "₼",
    country: "Azerbaijan",
  },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", country: "Georgia" },
  { code: "AMD", name: "Armenian Dram", symbol: "ք", country: "Armenia" },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    country: "Kazakhstan",
  },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", country: "Kyrgyzstan" },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    symbol: "сом",
    country: "Tajikistan",
  },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    symbol: "сўм",
    country: "Uzbekistan",
  },
  { code: "MNT", name: "Mongolian Tögrög", symbol: "₮", country: "Mongolia" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "Ks", country: "Myanmar" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", country: "Cambodia" },
  { code: "LAO", name: "Lao Kip", symbol: "₭", country: "Laos" },
  { code: "BND", name: "Brunei Dollar", symbol: "$", country: "Brunei" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", country: "Bhutan" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", country: "Maldives" },
  { code: "NPL", name: "Nepalese Rupee", symbol: "₨", country: "Nepal" },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    symbol: "Q",
    country: "Guatemala",
  },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", country: "Honduras" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", country: "Paraguay" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", country: "Bolivia" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$", country: "Uruguay" },
  { code: "PYR", name: "Paraguayan Guarani", symbol: "₲", country: "Paraguay" },
  {
    code: "SVC",
    name: "Salvadoran Colón",
    symbol: "₡",
    country: "El Salvador",
  },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    symbol: "C$",
    country: "Nicaragua",
  },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", country: "Hungary" },
  { code: "BWP", name: "Botswana Pula", symbol: "P", country: "Botswana" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", country: "Bulgaria" },
  {
    code: "BAM",
    name: "Bosnia and Herzegovina Convertible Mark",
    symbol: "KM",
    country: "Bosnia and Herzegovina",
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    symbol: "ден",
    country: "North Macedonia",
  },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", country: "Serbia" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", country: "Albania" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", country: "Moldova" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", country: "Angola" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", country: "Zimbabwe" },
  { code: "ZWB", name: "Zimbabwean Bond", symbol: "$", country: "Zimbabwe" },
  {
    code: "MZN",
    name: "Mozambican Metical",
    symbol: "MTn",
    country: "Mozambique",
  },
  { code: "BWP", name: "Botswana Pula", symbol: "P", country: "Botswana" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", country: "Lesotho" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", country: "Eswatini" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", country: "Malawi" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", country: "Zambia" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", country: "Zimbabwe" },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "FC",
    country: "Democratic Republic of the Congo",
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    country: "Cameroon",
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    symbol: "FCFA",
    country: "Côte d'Ivoire",
  },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", country: "Ghana" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "Sh", country: "Uganda" },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "Sh",
    country: "Tanzania",
  },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", country: "Rwanda" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", country: "Burundi" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", country: "Djibouti" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", country: "Comoros" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", country: "Eritrea" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", country: "Ethiopia" },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    symbol: "Le",
    country: "Sierra Leone",
  },
  { code: "LRD", name: "Liberian Dollar", symbol: "$", country: "Liberia" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", country: "Gambia" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", country: "Guinea" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", country: "Guinea" },
  {
    code: "CIV",
    name: "Ivorian Franc",
    symbol: "FC",
    country: "Côte d'Ivoire",
  },
  {
    code: "MRO",
    name: "Mauritanian Ouguiya",
    symbol: "UM",
    country: "Mauritania",
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    symbol: "UM",
    country: "Mauritania",
  },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", country: "Morocco" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", country: "Tunisia" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", country: "Algeria" },
  { code: "LYD", name: "Libyan Dinar", symbol: "د.ل", country: "Libya" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", country: "Egypt" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س", country: "Sudan" },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    symbol: "£",
    country: "South Sudan",
  },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", country: "Somalia" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", country: "Yemen" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", country: "Oman" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", country: "Kuwait" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "ب.د", country: "Bahrain" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", country: "Qatar" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", country: "Saudi Arabia" },
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    country: "United Arab Emirates",
  },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", country: "Jordan" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", country: "Lebanon" },
  { code: "SYR", name: "Syrian Pound", symbol: "£", country: "Syria" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", country: "Iraq" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", country: "Iran" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", country: "Afghanistan" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", country: "Pakistan" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", country: "Bangladesh" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", country: "Sri Lanka" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", country: "Nepal" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", country: "Bhutan" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", country: "Maldives" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "Ks", country: "Myanmar" },
  { code: "THB", name: "Thai Baht", symbol: "฿", country: "Thailand" },
  { code: "LAO", name: "Lao Kip", symbol: "₭", country: "Laos" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", country: "Cambodia" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", country: "Vietnam" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", country: "Malaysia" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", country: "Singapore" },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    country: "Indonesia",
  },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", country: "Philippines" },
  { code: "BND", name: "Brunei Dollar", symbol: "$", country: "Brunei" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", country: "Taiwan" },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    country: "South Korea",
  },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", country: "Japan" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", country: "China" },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    country: "Hong Kong",
  },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", country: "Macau" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", country: "Brazil" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", country: "Mexico" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", country: "Argentina" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", country: "Chile" },
  { code: "COP", name: "Colombian Peso", symbol: "$", country: "Colombia" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", country: "Peru" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$", country: "Uruguay" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", country: "Paraguay" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", country: "Bolivia" },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    symbol: "Q",
    country: "Guatemala",
  },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", country: "Honduras" },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    symbol: "C$",
    country: "Nicaragua",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    symbol: "₡",
    country: "Costa Rica",
  },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", country: "Panama" },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "$",
    country: "Dominican Republic",
  },
  { code: "JMD", name: "Jamaican Dollar", symbol: "$", country: "Jamaica" },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    symbol: "$",
    country: "Trinidad and Tobago",
  },
  { code: "BBD", name: "Barbadian Dollar", symbol: "$", country: "Barbados" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "$", country: "Bahamas" },
  { code: "BZD", name: "Belize Dollar", symbol: "$", country: "Belize" },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    symbol: "$",
    country: "Antigua and Barbuda",
  },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", country: "Suriname" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "$", country: "Guyana" },
  { code: "FJD", name: "Fijian Dollar", symbol: "$", country: "Fiji" },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    symbol: "K",
    country: "Papua New Guinea",
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    symbol: "$",
    country: "Solomon Islands",
  },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt", country: "Vanuatu" },
  {
    code: "NCX",
    name: "New Caledonian Franc",
    symbol: "FCFP",
    country: "New Caledonia",
  },
  {
    code: "XPF",
    name: "CFP Franc",
    symbol: "FCFP",
    country: "French Polynesia",
  },
  { code: "MUR", name: "Mauritian Rupee", symbol: "Rs", country: "Mauritius" },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    symbol: "Rs",
    country: "Seychelles",
  },
  { code: "MUR", name: "Mauritian Rupee", symbol: "Rs", country: "Mauritius" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", country: "Lesotho" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", country: "Eswatini" },
  { code: "BWP", name: "Botswana Pula", symbol: "P", country: "Botswana" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", country: "Zimbabwe" },
  { code: "ZWB", name: "Zimbabwean Bond", symbol: "$", country: "Zimbabwe" },
  {
    code: "MZN",
    name: "Mozambican Metical",
    symbol: "MTn",
    country: "Mozambique",
  },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", country: "Angola" },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "FC",
    country: "Democratic Republic of the Congo",
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    country: "Cameroon",
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    symbol: "FCFA",
    country: "Côte d'Ivoire",
  },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", country: "Ghana" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "Sh", country: "Uganda" },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "Sh",
    country: "Tanzania",
  },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", country: "Rwanda" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", country: "Burundi" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", country: "Djibouti" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", country: "Comoros" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", country: "Eritrea" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", country: "Ethiopia" },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    symbol: "Le",
    country: "Sierra Leone",
  },
  { code: "LRD", name: "Liberian Dollar", symbol: "$", country: "Liberia" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", country: "Gambia" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", country: "Guinea" },
  {
    code: "MRO",
    name: "Mauritanian Ouguiya",
    symbol: "UM",
    country: "Mauritania",
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    symbol: "UM",
    country: "Mauritania",
  },
  {
    code: "TMT",
    name: "Turkmenistan Manat",
    symbol: "m",
    country: "Turkmenistan",
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    symbol: "сом",
    country: "Tajikistan",
  },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", country: "Kyrgyzstan" },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    symbol: "сўм",
    country: "Uzbekistan",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    country: "Kazakhstan",
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "₼",
    country: "Azerbaijan",
  },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", country: "Georgia" },
  { code: "AMD", name: "Armenian Dram", symbol: "ք", country: "Armenia" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", country: "Moldova" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", country: "Albania" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", country: "Serbia" },
  {
    code: "MKD",
    name: "Macedonian Denar",
    symbol: "ден",
    country: "North Macedonia",
  },
  {
    code: "BAM",
    name: "Bosnia and Herzegovina Convertible Mark",
    symbol: "KM",
    country: "Bosnia and Herzegovina",
  },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", country: "Croatia" },
  { code: "RON", name: "Romanian Leu", symbol: "Lei", country: "Romania" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", country: "Belarus" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr", country: "Iceland" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", country: "Norway" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", country: "Denmark" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", country: "Sweden" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", country: "Switzerland" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", country: "Poland" },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    country: "Czech Republic",
  },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", country: "Hungary" },
  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    country: "United Kingdom",
  },
  { code: "EUR", name: "Euro", symbol: "€", country: "European Union" },
  { code: "USD", name: "US Dollar", symbol: "$", country: "United States" },
];

// Date format options
export const DATE_FORMATS = [
  { value: "DD/MM/YYYY", label: "DD/MM/YYYY" },
  { value: "MM/DD/YYYY", label: "MM/DD/YYYY" },
  { value: "YYYY-MM-DD", label: "YYYY-MM-DD" },
];

// Language options
export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
  { code: "bn", name: "Bengali" },
  { code: "npl", name: "Nepali" },
];

// Theme options
export const THEMES = [
  { value: "light", label: "Light Mode", icon: "Sun" },
  { value: "dark", label: "Dark Mode", icon: "Moon" },
];
